# Generated by Django 5.2.5 on 2025-08-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FretesWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete_id', models.CharField(max_length=255)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'verbose_name': 'Frete Webhook',
                'verbose_name_plural': 'Fretes Webhooks',
            },
        ),
    ]
