# Generated by Django 5.2.5 on 2025-08-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfeSenacWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nfe', models.CharField(max_length=255)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'verbose_name': 'NF-e Senac',
                'verbose_name_plural': 'NF-es Senac',
            },
        ),
    ]
