# Generated by Django 5.2.5 on 2025-08-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_nfesenacwebhook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NfeSenacWebhook',
            new_name='NfeWebhook',
        ),
        migrations.AlterModelOptions(
            name='nfewebhook',
            options={'verbose_name': 'NF-e Senac', 'verbose_name_plural': 'NF-e Senac'},
        ),
    ]
