# Generated by Django 5.2.5 on 2025-08-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_rename_nfesenacwebhook_nfewebhook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfewebhook',
            options={'verbose_name': 'NF-e Webhook', 'verbose_name_plural': 'NF-e Webhook'},
        ),
    ]
