services:
  web:
    build: .
    container_name: django_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file: 
      - .env
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # painel web
      - "5672:5672"    # conexão Celery
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A core worker -l info
    restart: always
    volumes:
      - .:/app
    env_file: 
      - .env
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  celery-beat:
    build: .
    command: celery -A core beat -l info
    restart: always
    volumes:
      - .:/app
    env_file: 
      - .env
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

volumes:
  rabbitmq_data:
  redis_data:
