services:
  web:
    build: .
    container_name: django_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # painel web
      - "5672:5672"    # conexão Celery
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery:
    build: .
    command: celery -A core worker -l info
    restart: always
    volumes:
      - .:/app
    env_file: 
      - .env
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      rabbitmq:
        condition: service_started

  celery-beat:
    build: .
    command: celery -A core beat -l INFO
    restart: always
    volumes:
      - .:/app
      - celery_beat_data:/app/celerybeat-data  # persistência do arquivo SQLite
    env_file: 
      - .env
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      rabbitmq:
        condition: service_started

volumes:
  rabbitmq_data:
  celery_beat_data:
