"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Inicializar environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w1653c-e=vpk_#^d-bbfg2538tnrn(uq25ib6hahj&8@l^5-_+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    # apps padrões do Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # terceiros
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    'rest_framework.authtoken',
    'django_celery_results',
    'django_celery_beat',

    # Nossos apps
    'usuarios',
    'integracoes',
    'webhooks',
    'webponto',
    'fretes',
    "notafiscal",
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'QuickDelivery API',
    'DESCRIPTION': 'Documentação da API',
    'VERSION': '1.0.0',
    'SECURITY': [{'TokenAuth': []}],
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
from decouple import config
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='3306'),
        "OPTIONS": {
            "charset": "utf8mb4",
            "use_unicode": True,
        },
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuracoes de e-mail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "naorespondertest@gmail.com"
EMAIL_HOST_PASSWORD = "98693021.Lg"
DEFAULT_FROM_EMAIL = "naorespondertest@gmail.com" 




# URL do RabbitMQ (definida no docker-compose)
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="amqp://guest:guest@localhost:5672//")

CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="django-db")

CELERY_TIMEZONE = 'America/Sao_Paulo'
CELERY_RESULT_BACKEND = 'django-db'

# Scheduler do Celery Beat (usando o django-celery-beat)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"




JAZZMIN_SETTINGS = {
    "site_title": "Sistema QuickDelivery",
    "site_header": "QuickDelivery",
    "site_brand": "QuickDelivery",  # Caminho relativo à pasta static
    "login_logo": "images/logo.jpg",  # Logo na tela de login
    "site_icon": "images/favicon-16x16.png",  # Ícone da aba do navegador
    "welcome_sign": "Sistema Adiministrativo da QuickDelivery",
    "copyright": "QuickDelivery © 2025",

    
"icons": {
        "auth.User": "fas fa-user",
        "groups.Group": "fas fa-users",
        "entregas.Pedido": "fas fa-box",
        "usuarios.Cliente": "fas fa-user-tag",
        "financeiro.Fatura": "fas fa-file-invoice-dollar",
    },

"side_menu": [
        {
            "app": "integracoes",
            "label": "Servico Senac",
            "icon": "fas fa-truck",
            "models": ["notafiscal.IntegracaoSenac"]
        },
        {
            "app": "usuarios",
            "label": "Usuários",
            "icon": "fas fa-users",
            "models": ["usuarios.Cliente"]
        },
        {
            "app": "financeiro",
            "label": "Financeiro",
            "icon": "fas fa-money-bill-wave",
            "models": ["financeiro.Fatura"]
        },
    ]

}
