# Generated by Django 5.2.5 on 2025-08-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('serie', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_emissao', models.DateTimeField()),
                ('data_saida_entrada', models.DateTimeField(blank=True, null=True)),
                ('tipo_operacao', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_total_produtos', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('valor_total_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('peso_total_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('nome_emitente', models.TextField(blank=True, null=True)),
                ('documento_emitente', models.TextField(blank=True, null=True)),
                ('nome_destinatario', models.TextField(blank=True, null=True)),
                ('documento_destinatario', models.TextField(blank=True, null=True)),
                ('endereco_destinatario', models.TextField(blank=True, null=True)),
                ('bairro_destinatario', models.TextField(blank=True, null=True)),
                ('cidade_destinatario', models.TextField(blank=True, null=True)),
                ('uf_destinatario', models.TextField(blank=True, null=True)),
                ('cep_destinatario', models.TextField(blank=True, null=True)),
                ('telefone_destinatario', models.TextField(blank=True, null=True)),
                ('email_destinatario', models.TextField(blank=True, null=True)),
                ('url_comprovante', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
    ]
