# Generated by Django 5.2.5 on 2025-08-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoSenac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('dados', models.JSONField()),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notafiscal.notafiscal')),
            ],
        ),
    ]
