# Generated by Django 5.2.5 on 2025-08-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0002_alter_notafiscal_bairro_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='nome_emitente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
