# Generated by Django 5.2.5 on 2025-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0002_integracaosenac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaosenac',
            name='id_nota_fiscal',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
