# Generated by Django 5.2.5 on 2025-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0003_alter_integracaosenac_id_nota_fiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integracaosenac',
            options={'verbose_name': 'Integração Senac', 'verbose_name_plural': 'Integrações Senac'},
        ),
        migrations.AddField(
            model_name='integracaosenac',
            name='chave_nfe',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
