# Generated by Django 5.2.5 on 2025-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0004_alter_integracaosenac_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaosenac',
            name='chave_nfe',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
