# Generated by Django 5.2.5 on 2025-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0005_alter_integracaosenac_chave_nfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracaosenac',
            name='id_nota_fiscal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
