# Generated by Django 5.2.5 on 2025-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0006_alter_integracaosenac_id_nota_fiscal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integracaosenac',
            options={'verbose_name': 'NF-e Integração Senac', 'verbose_name_plural': 'NF-es Integrações Senac'},
        ),
        migrations.AddField(
            model_name='integracaosenac',
            name='erro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
