# Generated by Django 5.2.5 on 2025-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete_id', models.CharField(max_length=20, unique=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('tipo_frete', models.CharField(blank=True, max_length=20, null=True)),
                ('previsao_entrega', models.CharField(blank=True, max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('agente_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_nfe', models.CharField(blank=True, max_length=20, null=True)),
                ('serie_nfe', models.CharField(blank=True, max_length=10, null=True)),
                ('chave_nfe', models.TextField(blank=True, null=True)),
                ('data_emissao_nfe', models.CharField(blank=True, max_length=20, null=True)),
                ('id_nfe', models.CharField(blank=True, max_length=20, null=True)),
                ('cte_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cte_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cte_key', models.TextField(blank=True, null=True)),
                ('data_emissao_cte', models.CharField(blank=True, max_length=20, null=True)),
                ('minuta_id', models.CharField(blank=True, max_length=20, null=True)),
                ('minuta_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('minuta_data_emissao', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_remetente', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_remetente', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_destinatario', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_destino', models.CharField(blank=True, max_length=5, null=True)),
                ('cep_destino', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco_destino', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_destinatario', models.CharField(blank=True, max_length=20, null=True)),
                ('email_destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('manifesto_id', models.CharField(blank=True, max_length=20, null=True)),
                ('manifesto_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('manifesto_data_emissao', models.CharField(blank=True, max_length=20, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_motorista', models.CharField(blank=True, max_length=20, null=True)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Fretes',
            },
        ),
    ]
